### PR TITLE
Fix full revoke bug

### LINKED ISSUE #636: Revoking the remainder of an investment causes an error updating portfolio
Error updating portfolio

### PR DESCRIPTION
**Pull request by ritmatter**
Fixes #636

### CODE REVIEW

File: api/routes/utils.js [hunk 1]
```diff
@@ -511,8 +511,8 @@ var utils = {
 
     // Update all fields for the toUser
     var toUserReps = this.updateTransactionToUser(toUser, fromUser, category.name, transaction.amount);
-    if (!toUserReps) {
-      return 'User is not an expert for category';
+    if (toUserReps === null) {
```
Comment (ritmatter) [inline api/routes/utils.js]: toUserReps hitting 0 from revoking all of the last investment was causing the error case to happen

**Comment by krazemon** [comment]
LGTM
