### PR TITLE
Fix empty investors and recount categories

### LINKED ISSUE #684: Recount experts, investors, and reps for each category
Data migration did not work properly

### LINKED ISSUE #685: Remove investors who have no investments for a given category
Data migration did not work properly

### PR DESCRIPTION
**Pull request by ritmatter**
Fixes #684
Fixes #685 

Do not run migration yet.

### CODE REVIEW

File: api/routes/utils.js [hunk 1]
```diff
@@ -435,7 +435,7 @@ var utils = {
     for (var i = 0; i < length; i++) {
       docs[i].save(function(err) {
         if (err) {
-          winston.log('error', 'utils.saveAll: error saving doc: %s', err);
+          winston.log('error', 'utils.saveAll: error saving doc: %s', err.toString());
```
Comment (ritmatter) [inline api/routes/utils.js]: Makes the message way clearer

**Comment by krazemon** [comment]
LGTM
