### PR TITLE
Fix naughty list

### LINKED ISSUE #573: BLOCKING: Naughty list is too severe
No requests can go through because everything is flagged as inappropriate content

### PR DESCRIPTION
**Pull request by ritmatter**
Fixes #573

### CODE REVIEW

File: config/censor.js [hunk 1]
```diff
@@ -7,12 +7,49 @@ var util = require('util');
...
+    var isNaughtyWord = function(word) {
+      for (var i = 0; i < length; i++) {
+        if (word === naughtylist[i]) {
+          return true;
+        }
+      }
+      return false;
+    };
+
+    // Examine req.params
```
Comment (krazemon) [inline config/censor.js]: Looks good, but we do need to be careful about for ... in.
See [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in)'s section on hasOwnProperty for an explanation of why. It's totally correct in this case, just wanted to alert you to the danger's of for ... in.

**Comment by krazemon** [comment]
LGTM
